### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [MaksimBorovik/1st#1]
Отсутствие скроллбара считаю ошибкой.
можете заменить стандартный, но убрать его - нельзя.

цвет и толщина не соответствуют макету.
![image](https://user-images.githubusercontent.com/8464662/60380971-6d1d1c00-9a56-11e9-8f05-4f76adc11ab9.png)

оутлайна в макете нет.
цвет не соответствует.
![image](https://user-images.githubusercontent.com/8464662/60380985-8cb44480-9a56-11e9-80de-c89e61573b28.png)

меню расположено некорректно.
![image](https://user-images.githubusercontent.com/8464662/60381001-b8372f00-9a56-11e9-9d6d-0651666885aa.png)

размеры шрифта и картинки не соответствуют.
![image](https://user-images.githubusercontent.com/8464662/60381023-ef0d4500-9a56-11e9-81e4-d6c013fbb27a.png)

некорректная сетка
![image](https://user-images.githubusercontent.com/8464662/60381047-457a8380-9a57-11e9-8200-26b0bf647a6b.png)

**Comment by MaksimBorovik** [comment]
have fixed all these minor bugs

**Comment by Alecto** [comment]
ссылку на страницу можно?

чт, 4 лип. 2019 о 17:07 MaksimBorovik <notifications@github.com> пише:

**Comment by MaksimBorovik** [comment]
https://maksimborovik.github.io/1st/

**Comment by Alecto** [comment]
фон не соответствует
![image](https://user-images.githubusercontent.com/8464662/60704697-d648d780-9f0d-11e9-9158-0725d4f38fd3.png)
![image](https://user-images.githubusercontent.com/8464662/60704723-e8c31100-9f0d-11e9-9f02-313a90cb3bdb.png)

минимально - вся высота окна
![image](https://user-images.githubusercontent.com/8464662/60704790-1b6d0980-9f0e-11e9-803f-bf514a90d0d8.png)

чем обосновано превышение высоты окна?
![image](https://user-images.githubusercontent.com/8464662/60704856-48212100-9f0e-11e9-9bb8-034fd51a1958.png)

**Comment by Alecto** [comment]
увидел письмо.
https://github.com/MaksimBorovik/1st/issues/1

пт, 5 лип. 2019 о 10:17 MaksimBorovik <notifications@github.com> пише:

**Comment by MaksimBorovik** [comment]
все делал исходя из шаблона, сейчас скринов скину)

**Comment by Alecto** [comment]
проверил, действительно.
фон пропускайте.

что касается высоты - в макете высота соответствует 100% размера окна, а не
пикселям.

пт, 5 лип. 2019 о 10:22 MaksimBorovik <notifications@github.com> пише:

**Comment by MaksimBorovik** [comment]
1. Subscribe - моя ошибка, не знаю как я её мог пропустить

2. View all posts... тут явно другой цвет
![2](https://user-images.githubusercontent.com/51057254/60705226-3be99380-9f0f-11e9-95fa-5c041fbe3ca6.JPG)

3. Размеры окон брал с макета. Хорошо, поменяю под 100vh

**Comment by Alecto** [comment]
фоны - ошибка.
макет исправлен и обновлен, артборды перегенерированы.
в принципе, можете оставить как есть, но я бы все такие советовал изменить
фон кнопки перед футером.

пт, 5 лип. 2019 о 10:34 MaksimBorovik <notifications@github.com> пише:

**Comment by MaksimBorovik** [comment]
Исправил значение высоты шапки и цвет кнопок

Размеры шапки брал с макета для того чтобы было удобнее по шаблону выстраивать блоки с помощью наложения картинки через perfectPixel

**Comment by Alecto** [comment]
текст в кнопке прыгает при наведении
![image](https://user-images.githubusercontent.com/8464662/60797644-52deee80-a178-11e9-8f35-c4d3f0838658.png)

как по мне - слишком яркий текст и подчеркивание для плейсхолдера и подчеркивания элемента в фокусе, как минимум - плэйсхолдер хочется "притушить", чтобы он не сливался с введенным текстом.
![image](https://user-images.githubusercontent.com/8464662/60797706-7a35bb80-a178-11e9-86d8-803f03104eaa.png)
в макете поведение не совсем очевидно, потому что и введенный текст и плейсхолдер имеют одинаковые значения.
менять или нет - решайте сами.

исправьте мелкий баг с прыганием и на этом финиш, работа принята.
